[package]
name           = "prometheus_exporter_base"
version        = "0.30.2"
authors        = ["Francesco Cogno <francesco.cogno@outlook.com>"]
edition        = "2018"
description    = "Prometheus Rust exporters base crate with boilerplate"

readme         = "README.md"
license        = "MIT"
repository     = "https://github.com/MindFlavor/prometheus_exporter_base"
documentation  = "https://github.com/MindFlavor/prometheus_exporter_base"
homepage       = "https://github.com/MindFlavor/prometheus_exporter_base"

keywords       = ["prometheus", "exporter"]
categories     = ["database"]

[dependencies]
log                  = "0.4"
env_logger           = "0.7.1"
futures-util-preview = "0.3.0-alpha.19"
clap                 = "2.33"
serde                = "1.0"
serde_json           = "1.0"
failure              = "0.1"
hyper                = { version        = "0.13.0-alpha.4" , features = ["unstable-stream"] }
hyper-rustls         = { version        = "0.19.0-alpha.3" , features = [] }
http                 = "0.1"
num                  = "0.2"

[dev-dependencies]
futures-util         = "0.3.1"
tokio                = "0.2.0-alpha.6"
