[package]
name           = "prometheus_exporter_base"
version        = "0.5.0"
authors        = ["Francesco Cogno <francesco.cogno@outlook.com>"]
edition        = "2018"
description    = "Prometheus Rust exporters base crate with boilerplate"

readme         = "README.md"
license        = "MIT"
repository     = "https://github.com/MindFlavor/prometheus_exporter_base"
documentation  = "https://github.com/MindFlavor/prometheus_exporter_base"
homepage       = "https://github.com/MindFlavor/prometheus_exporter_base"

keywords       = ["prometheus", "exporter"]
categories     = ["database"]

[dependencies]
log            = "*"
env_logger     = "*"
futures-preview = { version = " = 0.3.0-alpha.18", features = ["compat"] }
clap           = "*"
serde          = "*"
serde_json     = "*"
failure        = "*"
hyper          = "*"
http           = "*"
hyper-rustls   = "*"
num	       = "*"
